# You're free to change the jobs and the workflow logic as needed.
# Doc: https://circleci.com/docs/2.0/getting-started/#running-your-first-circleci-build
version: 2.1
parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

orbs:
  python: circleci/python@1.5.0

jobs:
  when: << pipeline.parameters.GHA_Action >>
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: make install test
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: make install beanstalk

workflows:
 version: 2
 deploy-server:
   jobs:
     - test
     - deploy:
         requires:
           - test
